### ISSUE TITLE
表单展示页

### ISSUE THREAD

**Issue by crazyggboom** [maoyl/el-form-design#16]
问下能不能做个提交表单后的展示页，把 input select变成 {{ value }}，checkbox disabled掉，这样一个表单展示页，麻烦啦

**Comment by maoyl** [comment]
源码给出来了&nbsp; 你可以直接在上面改


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "maoyl/el-form-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月7日(星期三) 上午10:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[maoyl/el-form-design] 表单展示页 (#16)





 
问下能不能做个提交表单后的展示页，把 input select变成 {{ value }}，checkbox disabled掉，这样一个表单展示页，麻烦啦

**Comment by crazyggboom** [comment]
好的好的，谢啦
